[package]
name = "log-graph"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.4", features = ["derive"] }
log = "0.4.21"
tiny-skia = "0.11.4"
tiny-skia-path = "0.11.4"

